# Generated by Django 4.1.5 on 2023-04-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_remove_workorder_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='title',
        ),
    ]
