# Generated by Django 4.1.5 on 2023-04-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_remove_workorder_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
