# Generated by Django 4.1.5 on 2023-04-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_workorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
