# Generated by Django 4.1.5 on 2023-04-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shoppingcartitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='price',
            new_name='shopping_cart_item_price',
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='work_order_item_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
